#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 3.3.{build}

# skip_non_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image: Visual Studio 2017

clone_depth: 5                      # clone entire repository history if not defined

nuget:
  account_feed: false
  project_feed: true
  disable_publish_on_pr: true     # disable publishing of .nupkg artifacts to account/project feeds for pull request builds

#---------------------------------#
#       build configuration       #
#---------------------------------#

configuration: Release

build_script:
  - dotnet build -c Release

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: '**\*.nupkg'

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:
  - provider: NuGet
    api_key:
      secure: dOHsapcNmgo9wYl3WZ7bMNYSHxsSoevt93gVUvXpsM0Q/T7Pwb+735XDoMiFybhM
    artifact: /.*\.nupkg/           # upload all NuGet packages to NuGet
    on:
      APPVEYOR_REPO_TAG: true       # deploy on tag push only

  - provider: GitHub
    auth_token:
      secure: 1vgrwXCK2yVSpvRrKMBTJiHtjceoS6czEauI4krHevc23B7iZ5wixYiDV9Lrf1Bj
    description: Draft release {APPVEYOR_REPO_TAG_NAME}
    artifact: /.*\.nupkg/           # upload all NuGet packages to release assets
    draft: true
    prerelease: false
    on:
      APPVEYOR_REPO_TAG: true       # deploy on tag push only
