#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 3.2.{build}

skip_non_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image: Visual Studio 2017

clone_depth: 5                      # clone entire repository history if not defined

nuget:
  account_feed: false
  project_feed: true
  disable_publish_on_pr: true     # disable publishing of .nupkg artifacts to account/project feeds for pull request builds

#---------------------------------#
#       build configuration       #
#---------------------------------#

configuration: Release

build_sript:
  - dotnet build -c Release

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: '**\*.nupkg'

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:
  - provider: NuGet
    api_key:
      secure: YYlVeoqkOM5F7xNXiPB52zZITqMG7WAcnqJwRbqFyuJjksrMV+olBl01RN9uFyyA
    artifact: /.*\.nupkg/           # upload all NuGet packages to NuGet
    on:
      branch: master

    # Deploy to GitHub Releases
  - provider: GitHub
    auth_token:
      secure: 0Gv+Vf6G1OTXyPjYQEPbAS3Ppf3JjVAwXuqCF+lvXfJ5+2EyzbSYUQKmburDzqlM
    description: Draft release
    artifact: /.*\.nupkg/           # upload all NuGet packages to release assets
    draft: true
    prerelease: false
    on:
      branch: master                # release from master branch only
      APPVEYOR_REPO_TAG: true       # deploy on tag push only